In [2]:
import pandas as pd

neg_data = pd.read_excel(r"D:\Users\Administrator\source\repos\ML_DL_DA\data_09\data_09\data\neg.xls", header=None)
print("len(neg_data):", len(neg_data))
print(neg_data.head())


len(neg_data): 10428
                                                   0
0  做为一本声名在外的流行书，说的还是广州的外企，按道理应该和我的生存环境差不多啊。但是一看之下...
1  作者有明显的自恋倾向，只有有老公养不上班的太太们才能像她那样生活。很多方法都不实用，还有抄袭...
2  作者完全是以一个过来的自认为是成功者的角度去写这个问题，感觉很不客观。虽然不是很喜欢，但是，...
3       作者提倡内调，不信任化妆品，这点赞同。但是所列举的方法太麻烦，配料也不好找。不是太实用。
4                  作者的文笔一般，观点也是和市面上的同类书大同小异，不推荐读者购买。


In [4]:
pos_data = pd.read_excel(r"D:\Users\Administrator\source\repos\ML_DL_DA\data_09\data_09\data\pos.xls", header=None)
print("len(pos_data):", len(pos_data))
pos_data.head()


len(pos_data): 10679


0
0  做父母一定要有刘墉这样的心态，不断地学习，不断地进步，不断地给自己补充新鲜血液，让自己保持一...
1  作者真有英国人严谨的风格，提出观点、进行论述论证，尽管本人对物理学了解不深，但是仍然能感受到...
2  作者长篇大论借用详细报告数据处理工作和计算结果支持其新观点。为什么荷兰曾经县有欧洲最高的生产...
3  作者在战几时之前用了＂拥抱＂令人叫绝．日本如果没有战败，就有会有美军的占领，没胡官僚主义的延...
4  作者在少年时即喜阅读，能看出他精读了无数经典，因而他有一个庞大的内心世界。他的作品最难能可贵...

In [6]:
comments_data = pd.read_csv(r"D:\Users\Administrator\source\repos\ML_DL_DA\data_09\data_09\comments.csv")
print("len(comments_data):", len(comments_data))
comments_data.head()

len(comments_data): 12376


评论ID                               评论内容
0  16512                               还不错啊
1  16515         实验环境无法进行输入，可能是网络原因吧，或者其他问题
2  16518                                abc
3  16521  因为所在网络不稳定，当网络出现掉线后，实验楼界面就无法点击和输入了
4  16524                           很不错，很好理解

In [10]:
import jieba
import numpy as np

# 加载语料库文件，并导入数据
neg_data = pd.read_excel(r"D:\Users\Administrator\source\repos\ML_DL_DA\data_09\data_09\data\neg.xls", header=None)
pos_data = pd.read_excel(r"D:\Users\Administrator\source\repos\ML_DL_DA\data_09\data_09\data\pos.xls", header=None)



In [9]:
pos_data[0]

0        做父母一定要有刘墉这样的心态，不断地学习，不断地进步，不断地给自己补充新鲜血液，让自己保持一...
1        作者真有英国人严谨的风格，提出观点、进行论述论证，尽管本人对物理学了解不深，但是仍然能感受到...
2        作者长篇大论借用详细报告数据处理工作和计算结果支持其新观点。为什么荷兰曾经县有欧洲最高的生产...
3        作者在战几时之前用了＂拥抱＂令人叫绝．日本如果没有战败，就有会有美军的占领，没胡官僚主义的延...
4        作者在少年时即喜阅读，能看出他精读了无数经典，因而他有一个庞大的内心世界。他的作品最难能可贵...
                               ...                        
10674                                                   好评
10675                                                   好评
10676                                                   好评
10677                                                   好评
10678                                                   好评
Name: 0, Length: 10679, dtype: object

In [11]:
neg_data[0]

0        做为一本声名在外的流行书，说的还是广州的外企，按道理应该和我的生存环境差不多啊。但是一看之下...
1        作者有明显的自恋倾向，只有有老公养不上班的太太们才能像她那样生活。很多方法都不实用，还有抄袭...
2        作者完全是以一个过来的自认为是成功者的角度去写这个问题，感觉很不客观。虽然不是很喜欢，但是，...
3             作者提倡内调，不信任化妆品，这点赞同。但是所列举的方法太麻烦，配料也不好找。不是太实用。
4                        作者的文笔一般，观点也是和市面上的同类书大同小异，不推荐读者购买。
                               ...                        
10423           安装我自己花了500多，美的够黑心的，真的是烦心，安装的售后叼的要死！差评！！！！！
10424                东西不错，售后太差，安装一个热水器400块钱，像话吗？钱给完了发现被黑了！
10425    碰到最差的、最骗人的卖家，好吧，我倒霉！这个卖家太不厚道了，显示所在地上海，我买这个热水器选...
10426                                      宝贝不错，物流也不错，售后差，
10427    美的售后太垃圾，其他售后都是两小时回电话，美的是24小时，结果超过市区不到五公里问我收五十，...
Name: 0, Length: 10428, dtype: object

In [14]:
def word_cut(x): return jieba.lcut(x)

# 'float' object has no attribute 'decode'
# pos_data['words'] = pos_data[0].apply(word_cut)
# neg_data['words'] = neg_data[0].apply(word_cut)

pos_data = pos_data.astype(str)
neg_data = neg_data.astype(str)
pos_data['words'] = pos_data[0].apply(word_cut).astype(str)
neg_data['words'] = neg_data[0].apply(word_cut).astype(str)

In [15]:
pos_data['words']

0        ['做', '父母', '一定', '要', '有', '刘墉', '这样', '的', '...
1        ['作者', '真有', '英国人', '严谨', '的', '风格', '，', '提出'...
2        ['作者', '长篇大论', '借用', '详细', '报告', '数据处理', '工作',...
3        ['作者', '在', '战', '几时', '之前', '用', '了', '＂', '拥...
4        ['作者', '在', '少年', '时即', '喜', '阅读', '，', '能', '...
                               ...                        
10674                                               ['好评']
10675                                               ['好评']
10676                                               ['好评']
10677                                               ['好评']
10678                                               ['好评']
Name: words, Length: 10679, dtype: object

In [16]:
neg_data

0  \
0      做为一本声名在外的流行书，说的还是广州的外企，按道理应该和我的生存环境差不多啊。但是一看之下...   
1      作者有明显的自恋倾向，只有有老公养不上班的太太们才能像她那样生活。很多方法都不实用，还有抄袭...   
2      作者完全是以一个过来的自认为是成功者的角度去写这个问题，感觉很不客观。虽然不是很喜欢，但是，...   
3           作者提倡内调，不信任化妆品，这点赞同。但是所列举的方法太麻烦，配料也不好找。不是太实用。   
4                      作者的文笔一般，观点也是和市面上的同类书大同小异，不推荐读者购买。   
...                                                  ...   
10423         安装我自己花了500多，美的够黑心的，真的是烦心，安装的售后叼的要死！差评！！！！！   
10424              东西不错，售后太差，安装一个热水器400块钱，像话吗？钱给完了发现被黑了！   
10425  碰到最差的、最骗人的卖家，好吧，我倒霉！这个卖家太不厚道了，显示所在地上海，我买这个热水器选...   
10426                                    宝贝不错，物流也不错，售后差，   
10427  美的售后太垃圾，其他售后都是两小时回电话，美的是24小时，结果超过市区不到五公里问我收五十，...   

                                                   words  
0      ['做', '为', '一本', '声名在外', '的', '流行', '书', '，', ...  
1      ['作者', '有', '明显', '的', '自恋', '倾向', '，', '只有', ...  
2      ['作者', '完全', '是', '以', '一个', '过来', '的', '自', '...  
3      ['作者', '提倡', '内', '调', '，', '不', '信任', '化妆品', ...  
4      ['作者', '的', '文笔', '一般', '，', '观点', '也', '是', '...  
...                                                  ...  
10423  ['安装', '我', '自己', '花', '了', '500', '多', '，', '...  
10424  ['东西', '不错', '，', '售后', '太', '差', '，', '安装', '...  
10425  ['碰到', '最差', '的', '、', '最', '骗人', '的', '卖家', '...  
10426  ['宝贝', '不错', '，', '物流', '也', '不错', '，', '售后', ...  
10427  ['美的', '售后', '太', '垃圾', '，', '其他', '售后', '都', ...  

[10428 rows x 2 columns]

In [17]:
# 使用 1 表示积极情绪，0 表示消极情绪，并完成数组拼接
x = np.concatenate((pos_data['words'], neg_data['words']))
y = np.concatenate((np.ones(len(pos_data)), np.zeros(len(neg_data))))

# 将 Ndarray 保存为二进制文件备用
np.save('X_train.npy', x)
np.save('y_train.npy', y)

print('done.')

done.


In [18]:
np.load('X_train.npy', allow_pickle=True)

array(["['做', '父母', '一定', '要', '有', '刘墉', '这样', '的', '心态', '，', '不断', '地', '学习', '，', '不断', '地', '进步', '，', '不断', '地', '给', '自己', '补充', '新鲜血液', '，', '让', '自己', '保持', '一颗', '年轻', '的', '心', '。', '我', '想', '，', '这', '是', '他', '能', '很', '好', '的', '和', '孩子', '沟通', '的', '一个', '重要', '因素', '。', '读', '刘墉', '的', '文章', '，', '总能', '让', '我', '看到', '一个', '快乐', '的', '平易近人', '的', '父亲', '，', '他', '始终', '站', '在', '和', '孩子', '同样', '的', '高度', '，', '给', '孩子', '创造', '着', '一个', '充满', '爱', '和', '自由', '的', '生活', '环境', '。', '很', '喜欢', '刘墉', '在', '字里行间', '流露出', '的', '做', '父母', '的', '那种', '小', '狡黠', '，', '让', '人', '总是', '忍俊不禁', '，', '父母', '和', '子女', '之间', '有时候', '也', '是', '一种', '战斗', '，', '武力', '争斗', '过于', '低级', '了', '，', '智力', '较量', '才', '更', '有', '趣味', '。', '所以', '，', '做', '父母', '的', '得', '加把劲', '了', '，', '老', '思想', '老', '观念', '注定', '会', '一败涂地', '，', '生命不息', '，', '学习', '不止', '。', '家庭教育', '，', '真的', '是', '乐在其中', '。']",
       "['作者', '真有', '英国人', '严谨', '的', '风格', '，', '提出', '观点', '、', '进行', '论述', '论证', '，', '尽管'

In [19]:
!pip install gensim

^C


In [21]:
# Word2Vec 处理
from gensim.models.word2vec import Word2Vec
import warnings
warnings.filterwarnings('ignore')  # 忽略警告

# 导入上面保存的分词数组
X_train = np.load('X_train.npy', allow_pickle=True)

X_train


array(["['做', '父母', '一定', '要', '有', '刘墉', '这样', '的', '心态', '，', '不断', '地', '学习', '，', '不断', '地', '进步', '，', '不断', '地', '给', '自己', '补充', '新鲜血液', '，', '让', '自己', '保持', '一颗', '年轻', '的', '心', '。', '我', '想', '，', '这', '是', '他', '能', '很', '好', '的', '和', '孩子', '沟通', '的', '一个', '重要', '因素', '。', '读', '刘墉', '的', '文章', '，', '总能', '让', '我', '看到', '一个', '快乐', '的', '平易近人', '的', '父亲', '，', '他', '始终', '站', '在', '和', '孩子', '同样', '的', '高度', '，', '给', '孩子', '创造', '着', '一个', '充满', '爱', '和', '自由', '的', '生活', '环境', '。', '很', '喜欢', '刘墉', '在', '字里行间', '流露出', '的', '做', '父母', '的', '那种', '小', '狡黠', '，', '让', '人', '总是', '忍俊不禁', '，', '父母', '和', '子女', '之间', '有时候', '也', '是', '一种', '战斗', '，', '武力', '争斗', '过于', '低级', '了', '，', '智力', '较量', '才', '更', '有', '趣味', '。', '所以', '，', '做', '父母', '的', '得', '加把劲', '了', '，', '老', '思想', '老', '观念', '注定', '会', '一败涂地', '，', '生命不息', '，', '学习', '不止', '。', '家庭教育', '，', '真的', '是', '乐在其中', '。']",
       "['作者', '真有', '英国人', '严谨', '的', '风格', '，', '提出', '观点', '、', '进行', '论述', '论证', '，', '尽管'

In [23]:
# 训练 Word2Vec 浅层神经网络模型
# __init__() got an unexpected keyword argument 'size'
# w2v = Word2Vec(size=300, min_count=10)

w2v = Word2Vec(vector_size=300, min_count=10)
w2v.build_vocab(X_train)
w2v.train(X_train, total_examples=w2v.corpus_count, epochs=w2v.epochs)


(11627301, 37736940)

In [25]:
w2v

In [27]:
def sum_vec(text):
    # 对每个句子的词向量进行求和计算
    vec = np.zeros(300).reshape((1, 300))
    for word in text:
        try:
            vec += w2v.wv[word].reshape((1, 300))
        except KeyError:
            continue
    return vec



In [28]:

# 将词向量保存为 Ndarray
train_vec = np.concatenate([sum_vec(z) for z in X_train])
train_vec

array([[  36.11403902, -445.87417152, -234.12617199, ...,   88.10796945,
        -241.47652975,  154.60089931],
       [  10.27594731, -313.28048333, -196.29021642, ...,   90.32592389,
        -159.86556299,   98.37756178],
       [  12.28097865, -224.55445862, -137.78509241, ...,   54.12099384,
         -72.0740349 ,   72.3469837 ],
       ...,
       [ 117.14435632, -726.99526236, -434.37742688, ...,  167.60965992,
        -415.31785006,  250.92621808],
       [   7.25883931,  -28.01464622,  -13.18711416, ...,   -1.79423881,
         -19.6731239 ,    7.9172147 ],
       [  18.19591606, -127.16843668,  -80.27816623, ...,   13.67739376,
         -88.51699012,   39.82591897]])

In [29]:
# 保存 Word2Vec 模型及词向量
w2v.save('w2v_model.pkl')
np.save('X_train_vec.npy', train_vec)
print('done.')

done.


In [31]:
import joblib
from sklearn.tree import DecisionTreeClassifier

# 导入词向量为训练特征
X = np.load('X_train_vec.npy')
# 导入情绪分类作为目标特征
y = np.load('y_train.npy')
X,y

(array([[  36.11403902, -445.87417152, -234.12617199, ...,   88.10796945,
         -241.47652975,  154.60089931],
        [  10.27594731, -313.28048333, -196.29021642, ...,   90.32592389,
         -159.86556299,   98.37756178],
        [  12.28097865, -224.55445862, -137.78509241, ...,   54.12099384,
          -72.0740349 ,   72.3469837 ],
        ...,
        [ 117.14435632, -726.99526236, -434.37742688, ...,  167.60965992,
         -415.31785006,  250.92621808],
        [   7.25883931,  -28.01464622,  -13.18711416, ...,   -1.79423881,
          -19.6731239 ,    7.9172147 ],
        [  18.19591606, -127.16843668,  -80.27816623, ...,   13.67739376,
          -88.51699012,   39.82591897]]),
 array([1., 1., 1., ..., 0., 0., 0.]))

In [32]:
# 构建支持向量机分类模型
model = DecisionTreeClassifier()
# 训练模型
model.fit(X, y)
# 保存模型为二进制文件
joblib.dump(model, 'dt_model.pkl')


['dt_model.pkl']

In [35]:
# 读取 Word2Vec 并对新输入进行词向量计算
def sum_vec(words):
    # 读取 Word2Vec 模型
    w2v = Word2Vec.load('w2v_model.pkl')
    vec = np.zeros(300).reshape((1, 300))
    for word in words:
        try:
            vec += w2v.wv[word].reshape((1, 300))
        except KeyError:
            continue
    return vec


In [36]:
# 读取蓝桥云课评论
df = pd.read_csv(r"D:\Users\Administrator\source\repos\ML_DL_DA\data_09\data_09\comments.csv", header=0)
comment_sentiment = []
for string in df['评论内容']:
    # 对评论分词
    words = jieba.lcut(str(string))
    words_vec = sum_vec(words)
    # 读取支持向量机模型
    model = joblib.load('dt_model.pkl')
    result = model.predict(words_vec)
    comment_sentiment.append(result[0])

    # 实时返回积极或消极结果
    if int(result[0]) == 1:
        print(string, '[积极]')
    else:
        print(string, '[消极]')

# 将情绪结果合并到原数据文件中
merged = pd.concat([df, pd.Series(comment_sentiment, name='用户情绪')], axis=1)
pd.DataFrame.to_csv(merged, 'comment_sentiment.csv')  # 储存文件以备后用


还不错啊 [消极]
实验环境无法进行输入，可能是网络原因吧，或者其他问题 [积极]
abc [消极]
因为所在网络不稳定，当网络出现掉线后，实验楼界面就无法点击和输入了 [积极]
很不错，很好理解 [积极]
能不能自由选择学习章节 [消极]
连接远程库这块说的不够清楚 [积极]
挺不错的就是有视频就好多了 [消极]
浏览器打不开 [消极]
重启下 [消极]
神奇 [消极]
还要从头开始学 [消极]
ok [消极]
内容比较简单，容易上手 [积极]
... [消极]
很喜欢这个课程 [消极]
很全面，加上再看看鸟哥的私房菜肯定就没问题了！ [积极]
非常不错！ [消极]
平台好 [积极]
python基础 [消极]
非常值得练习的一些操作 [积极]
实验文档详细 [消极]
感觉一般般！ [消极]
好累。。 [积极]
为什么中文输不进去，导致程序无法运行 [消极]
挺好的~ [积极]
python基础下 [消极]
。。怎么算有效时间 [积极]
还在熟悉环境阶段 [消极]
很不错 [消极]
编译器不是很好用，有点不舒服 [消极]
自己还是太笨了 [消极]
越来越喜欢了！ [消极]
我靠思考的时间就不算学习时间了？ [积极]
对vim使用还是不太方便的 [积极]
简单 [消极]
又做了个有趣的实验~ [消极]
为什么说有些命令找不到  比如banner [积极]
可以  趣味不错 [积极]
感觉nice！ [消极]
不是很困难 [消极]
非常好 [积极]
有效学习时间不准确啊 [消极]
for有点特别 [消极]
挺好的 [积极]
代码规范很重要 [消极]
额。还有点不熟悉代码 [积极]
Interesting [消极]
加油吧！ [消极]
想继续学好编程 [消极]
教学环境很好，会更努力学习 [积极]
嗯 很好 [消极]
以为只要写代码的，毕竟很基础，没想到还要写报告，然后markdown也不会用又去搜语法。最后感觉实验报告也写完了应该就完了却说还有一个没完成。 [积极]
linux桌面环境，没啥 [消极]
挺好的 [积极]
很喜欢这种方式 希望你们坚持到底 越做越好 [积极]
linux不是很容易上手啊..... [消极]
加油 [消极]
延迟。。。。 [积极]
简单的了解了vim的基本操作，需要用的时候可以针对性进行搜索 [消极]
很详细 [消极]
测试测试测试测试测试