In [1]:
import numpy as np

a1 = np.array([1, 2, 3, 4])
a1


array([1, 2, 3, 4])

In [2]:
a1.shape

(4,)

In [3]:
a1.size

4

In [4]:
a1.dtype

dtype('int32')

In [5]:
a2 = np.array([[1.0, 2.5, 3], [0.5, 4, 9]])
a2

array([[1. , 2.5, 3. ],
       [0.5, 4. , 9. ]])

In [6]:
print(a2.shape)
print(a2.size)
print(a2.min())
print(a2.dtype)
print(type(a1))
print()

(2, 3)
6
0.5
float64
<class 'numpy.ndarray'>



In [7]:
a3 = np.arange(4)
a3

array([0, 1, 2, 3])

In [8]:
print(a3.ndim)

1


In [9]:
a4 = np.ones((4, 4), dtype=np.int64)
print(a4)
print(a4.dtype)
print(a4.ndim)
print(a4.shape)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int64
2
(4, 4)


In [10]:
a5 = np.zeros((2, 2))
a5

array([[0., 0.],
       [0., 0.]])

In [12]:
print(a5.dtype)
print(a5.ndim)

float64
2


In [13]:

a6 = np.empty((3, 3), dtype=np.int64)
print(a6.dtype)
print(a6.shape)
print(a6.ndim)
print()


int64
(3, 3)
2



当没有指定 dtype 类型时，多维数组元素类型默认是 float64。

In [14]:
a7 = np.ones((4, 3, 4))
print(a7)
print(a7.ndim)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3


In [15]:
a6 = np.arange(12)
print(a6)
print(a6.reshape(4, 3))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


reshape 方法的参数为指定数组形状的元组。

In [16]:
l = [1, 2, 3, 4, 5]
print(l[:2])
print(l[2:4])
print(l[1:5:2])

[1, 2]
[3, 4]
[2, 4]


In [17]:
a = np.arange(12)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
print(a[1:4])
print(a[1:10:2])


[1 2 3]
[1 3 5 7 9]


In [19]:
a[1:5] = -1
a

array([ 0, -1, -1, -1, -1,  5,  6,  7,  8,  9, 10, 11])

In [20]:
a[1:10:2] = 1
a

array([ 0,  1, -1,  1, -1,  1,  6,  1,  8,  1, 10, 11])

In [21]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
print(a[:, 0])
print(a[:, 1])

[0 4 8]
[1 5 9]


In [24]:
a[:, 1] = -1
a


array([[ 0, -1,  2,  3],
       [ 4, -1,  6,  7],
       [ 8, -1, 10, 11]])

In [25]:
a = np.arange(27).reshape(3, 3, 3)
a


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [26]:
a1 = a[1]
a1

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [27]:
a2 = a[1, 1]

a2

array([12, 13, 14])

In [28]:
a[:, 1]

array([[ 3,  4,  5],
       [12, 13, 14],
       [21, 22, 23]])

In [29]:
a[:, 1] = 1
a


array([[[ 0,  1,  2],
        [ 1,  1,  1],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [ 1,  1,  1],
        [15, 16, 17]],

       [[18, 19, 20],
        [ 1,  1,  1],
        [24, 25, 26]]])

In [30]:
a = np.arange(12).reshape(3, 4)
a += 2
a

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [31]:
a *= 2
a

array([[ 4,  6,  8, 10],
       [12, 14, 16, 18],
       [20, 22, 24, 26]])

In [34]:
a = np.arange(4).reshape(2, 2)
b = np.arange(4, 8).reshape(2, 2)
print(a)
print(b)
print(b-a)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]
[[4 4]
 [4 4]]


In [35]:
# 矩阵的乘法运算
a.dot(b)

array([[ 6,  7],
       [26, 31]])

In [36]:
a = np.arange(12).reshape(4, 3)
b = a > 5
b

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [37]:
a[b]

array([ 6,  7,  8,  9, 10, 11])

a.sum 计算多维数组的所有元素的和；
a.max 最大值计算；
a.min 最小值计算；
a.mean 平均值计算；
a.std 标准差计算；
a.var 方差计算；

In [40]:
print(a.sum())
print(a.max())
print(a.min())
print(a.mean())
print(a.std())
print(a.var())

66
11
0
5.5
3.452052529534663
11.916666666666666


In [41]:
# 统计每一列的和，并生成一个一纬度数组
a.sum(axis=0)

array([18, 22, 26])

In [42]:
# 统计每一行的和，并生成一个一纬度数组
a.sum(axis=1)

array([ 3, 12, 21, 30])

np.sqrt 开方运算；
np.dot 矩阵乘法；
np.sort 排序；
np.linalg 模块中包含了一些基本的线性代数计算函数；

In [43]:
import pandas as pd

s1 = pd.Series([1, 2, 3, 4, 5])
s1


0    1
1    2
2    3
3    4
4    5
dtype: int64

In [44]:
s2 = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
s2

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [45]:
s2.index.name = 'index'
s2.index


Index(['a', 'b', 'c', 'd', 'e'], dtype='object', name='index')

In [46]:
s2.index.name

'index'

In [47]:
df = pd.DataFrame(np.random.randn(4, 4), index=[
               'a', 'b', 'c', 'd'], columns=['A', 'B', 'C', 'D'])
df

A         B         C         D
a  0.660563  1.230580  0.388345  0.202278
b -1.568744  0.707311 -0.518252  0.397784
c -0.936242 -0.261383  2.941640  0.477112
d -0.679729  0.886500  0.511352 -0.487500

In [50]:
print(df.index)
print(df.columns)


Index(['a', 'b', 'c', 'd'], dtype='object')
Index(['A', 'B', 'C', 'D'], dtype='object')
<bound method DataFrame.dot of           A         B         C         D
a  0.660563  1.230580  0.388345  0.202278
b -1.568744  0.707311 -0.518252  0.397784
c -0.936242 -0.261383  2.941640  0.477112
d -0.679729  0.886500  0.511352 -0.487500>


In [51]:
s2 = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
s2

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [52]:
print("s2[0]:",s2[0])
print("s2['a']", s2['a'])
print("s2[0:3]", s2[0:3])
print("s2['a':'c']", s2['a':'c'])

s2[0]: 1
s2['a'] 1
s2[0:3] a    1
b    2
c    3
dtype: int64
s2['a':'c'] a    1
b    2
c    3
dtype: int64


In [53]:
s2.iloc[0:3]

a    1
b    2
c    3
dtype: int64

In [54]:
s2.loc['a':'c']

a    1
b    2
c    3
dtype: int64

In [55]:
print("df.A:", df.A)
print("df['A']:", df['A'])

df.A: a    0.660563
b   -1.568744
c   -0.936242
d   -0.679729
Name: A, dtype: float64
df['A']: a    0.660563
b   -1.568744
c   -0.936242
d   -0.679729
Name: A, dtype: float64


In [56]:
df[df.columns[0:2]]

A         B
a  0.660563  1.230580
b -1.568744  0.707311
c -0.936242 -0.261383
d -0.679729  0.886500

In [57]:
df.loc['a']

A    0.660563
B    1.230580
C    0.388345
D    0.202278
Name: a, dtype: float64

In [58]:
df.loc['a':'b']

A         B         C         D
a  0.660563  1.230580  0.388345  0.202278
b -1.568744  0.707311 -0.518252  0.397784

In [59]:
df.iloc[0]

A    0.660563
B    1.230580
C    0.388345
D    0.202278
Name: a, dtype: float64

In [60]:
df.loc[:, ['B', 'C', 'D']]

B         C         D
a  1.230580  0.388345  0.202278
b  0.707311 -0.518252  0.397784
c -0.261383  2.941640  0.477112
d  0.886500  0.511352 -0.487500

In [61]:
df.loc['a', 'A']

0.6605627822037515

In [62]:
df.loc['b':'c', 'B':'C']

B         C
b  0.707311 -0.518252
c -0.261383  2.941640

In [63]:
s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s1

a    1
b    2
c    3
d    4
dtype: int64

In [64]:
s2 = pd.Series([2, 3, 4, 5], index=['b', 'c', 'd', 'e'])
s2

b    2
c    3
d    4
e    5
dtype: int64

In [65]:
s1 + s2

a    NaN
b    4.0
c    6.0
d    8.0
e    NaN
dtype: float64

相同索引上的值会相加，但不重叠的索引引入 NaN 值，也就是缺失值。而缺失值会在运算中传播，所以最终结果也是 NaN 值。根据相同的索引进行自动计算，这就是自动对齐功能。

In [66]:
df1 = pd.DataFrame(np.arange(9).reshape(
    3, 3), columns=list('ABC'), index=list('abc'))
df1


A  B  C
a  0  1  2
b  3  4  5
c  6  7  8

In [67]:
df2 = pd.DataFrame(np.arange(12).reshape(
    3, 4), columns=list('ABDE'), index=list('bcd'))
df2

A  B   D   E
b  0  1   2   3
c  4  5   6   7
d  8  9  10  11

In [68]:
df1 + df2

A     B   C   D   E
a   NaN   NaN NaN NaN NaN
b   3.0   5.0 NaN NaN NaN
c  10.0  12.0 NaN NaN NaN
d   NaN   NaN NaN NaN NaN

In [69]:
df1.add(df2, fill_value=0)

A     B    C     D     E
a   0.0   1.0  2.0   NaN   NaN
b   3.0   5.0  5.0   2.0   3.0
c  10.0  12.0  8.0   6.0   7.0
d   8.0   9.0  NaN  10.0  11.0

In [70]:
df1 = pd.DataFrame(np.arange(9).reshape(
    3, 3), columns=list('ABC'), index=list('abc'))

df1

A  B  C
a  0  1  2
b  3  4  5
c  6  7  8

In [71]:
def f(x): return x.max() - x.min()


df1.apply(f)


A    6
B    6
C    6
dtype: int32

In [72]:
df1.apply(f, axis=1)

a    2
b    2
c    2
dtype: int32

定义 f 匿名函数，该匿名函数简单的返回列表的极差，然后首先通过 df.apply(f) 应用 f, 统计出每列的极差，接着通过传入 axis=1 参数，统计出每行的极差，如果想将某函数应用到每一个元素上，对于 DataFrame 数据可使用 df.applymap 方法，而对于 Series 数据可以使用 s.map 方法：

In [73]:
df1.applymap(lambda x: x+1)

A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [74]:
df1 = pd.DataFrame(np.arange(9).reshape(
    3, 3), columns=list('ABC'), index=list('abc'))

df1

A  B  C
a  0  1  2
b  3  4  5
c  6  7  8

In [75]:
df1.sum()

A     9
B    12
C    15
dtype: int64

In [76]:
df1.mean()

A    3.0
B    4.0
C    5.0
dtype: float64

In [77]:
df1.sum(axis=1)

a     3
b    12
c    21
dtype: int64

In [78]:
df1.describe()

A    B    C
count  3.0  3.0  3.0
mean   3.0  4.0  5.0
std    3.0  3.0  3.0
min    0.0  1.0  2.0
25%    1.5  2.5  3.5
50%    3.0  4.0  5.0
75%    4.5  5.5  6.5
max    6.0  7.0  8.0

count 元素值的数量；
mean 平均值；
std 标准差；
min 最小值；
25% 下四分位数；
50% 中位数；
75% 上四分位数；
max 最大值；

In [79]:
df1 = pd.DataFrame(np.random.randn(3, 3))
df1


0         1         2
0 -1.843246  0.826987  0.342655
1  1.325777  0.199151 -0.742956
2 -0.426779  0.067514 -0.963956

In [82]:
df2 = pd.DataFrame(np.random.randn(3, 3), index=[5, 6, 7])
df2


0         1         2
5  0.742835 -1.104834  0.604624
6  0.503377  0.988200  0.869446
7  0.170275 -0.002225 -1.052644

In [83]:
pd.concat([df1, df2])

0         1         2
0 -1.843246  0.826987  0.342655
1  1.325777  0.199151 -0.742956
2 -0.426779  0.067514 -0.963956
5  0.742835 -1.104834  0.604624
6  0.503377  0.988200  0.869446
7  0.170275 -0.002225 -1.052644

In [84]:
df1 = pd.DataFrame({'user_id': [5348, 13], 'course': [
                12, 45], 'minutes': [9, 36]})
df1

user_id  course  minutes
0     5348      12        9
1       13      45       36

In [85]:
df2 = pd.DataFrame({'course': [12, 45], 'name': ['Linux 基础入门', '数据分析']})
df2


course        name
0      12  Linux 基础入门
1      45        数据分析

In [86]:
pd.merge(df1, df2)

user_id  course  minutes        name
0     5348      12        9  Linux 基础入门
1       13      45       36        数据分析

通过字典创建两个数据集，当通过字段创建 DataFrame 数据集时，键名变成了列名。df1 和 df2 有共同的列 course, 当进行 merge 操作的时候 Pandas 会自动安装这列进行合并。
合并数据集时，有很多参数可以选择，比如选择在根据哪一列进行合并，合并的方式等，可以通过 help(pd.merge) 查看完整的帮助文档。
在 Pandas 中，也支持类似于数据库查询语句 GROUP BY 的功能，也就是按照某列进行分组，然后再分组上进行一些计算操作.

In [87]:
df = pd.DataFrame({'user_id': [5348, 13, 5348], 'course': [
               12, 45, 23], 'minutes': [9, 36, 45]})
df


user_id  course  minutes
0     5348      12        9
1       13      45       36
2     5348      23       45

In [88]:
df[df['user_id'] == 5348]['minutes']

0     9
2    45
Name: minutes, dtype: int64

In [89]:
df[df['user_id'] == 5348]

user_id  course  minutes
0     5348      12        9
2     5348      23       45

In [90]:
df[df['user_id'] == 5348]['minutes']

0     9
2    45
Name: minutes, dtype: int64

In [91]:
df[df['user_id'] == 5348]['minutes'].sum()

54

In [92]:
df[['user_id', 'minutes']]

user_id  minutes
0     5348        9
1       13       36
2     5348       45

In [93]:
df[['user_id', 'minutes']].groupby('user_id').sum()

minutes
user_id         
13            36
5348          54

datetime.datetime 代表时间对象；
datetime.date 代表某一天；
datetime.timedelta 代表两个 
datetime.datetime 对象之间的时间差；

In [94]:
from datetime import datetime, timedelta

d1 = datetime(2017, 8, 1)
d1


datetime.datetime(2017, 8, 1, 0, 0)

In [95]:
delta = timedelta(days=10)
d1 + delta

datetime.datetime(2017, 8, 11, 0, 0)

In [96]:
# 时间序列
from datetime import datetime

dates = [datetime(2018, 1, 1), datetime(2018, 1, 2),
         datetime(2018, 1, 3), datetime(2018, 1, 4)]

ts = pd.Series(np.random.randn(4), index=dates)
ts


2018-01-01    0.996701
2018-01-02    1.238223
2018-01-03    2.116374
2018-01-04    0.059768
dtype: float64

In [97]:
ts.index[0]

Timestamp('2018-01-01 00:00:00')

In [98]:
ts[ts.index[0]]

0.9967013376406357

In [99]:
ts['2018-01-01']

0.9967013376406357

In [100]:
ts['2019-01-01']

KeyError: '2019-01-01'

In [101]:
ts['2018/01/01']

0.9967013376406357

In [102]:
ts['1/1/2018']

0.9967013376406357

In [103]:
ts[datetime(2018, 1, 1)]

0.9967013376406357

start: 指定了日期范围的起始时间；
end: 指定了日期范围的结束时间；
periods: 指定了间隔范围，如果只是指定了 start 和 end 日期的其中一个，则需要改参数；
freq: 指定了日期频率，比如 
D 代表每天，
H 代表每小时，
M 代表月，这些频率字符前也可以指定一个整数，代表具体多少天，多少小时，比如 
5D 代表 5 天。还有一些其他的频率字符串，比如 
MS 代表每月第一天，
BM 代表每月最后一个工作日，或者是频率组合字符串，比如 
1h30min 代表 1 小时 30 分钟。

In [104]:
pd.date_range('2018-1-1', '2019', freq='M')

DatetimeIndex(['2018-01-31', '2018-02-28', '2018-03-31', '2018-04-30',
               '2018-05-31', '2018-06-30', '2018-07-31', '2018-08-31',
               '2018-09-30', '2018-10-31', '2018-11-30', '2018-12-31'],
              dtype='datetime64[ns]', freq='M')

In [105]:
pd.date_range('2018-1-1', '2018-12-1', freq='MS')

DatetimeIndex(['2018-01-01', '2018-02-01', '2018-03-01', '2018-04-01',
               '2018-05-01', '2018-06-01', '2018-07-01', '2018-08-01',
               '2018-09-01', '2018-10-01', '2018-11-01', '2018-12-01'],
              dtype='datetime64[ns]', freq='MS')

In [107]:
dates = pd.date_range('2018-1-1', '2018-1-2 23:00:00', freq='H')
print(dates)
ts = pd.Series(np.arange(len(dates)), index=dates)

ts.size

DatetimeIndex(['2018-01-01 00:00:00', '2018-01-01 01:00:00',
               '2018-01-01 02:00:00', '2018-01-01 03:00:00',
               '2018-01-01 04:00:00', '2018-01-01 05:00:00',
               '2018-01-01 06:00:00', '2018-01-01 07:00:00',
               '2018-01-01 08:00:00', '2018-01-01 09:00:00',
               '2018-01-01 10:00:00', '2018-01-01 11:00:00',
               '2018-01-01 12:00:00', '2018-01-01 13:00:00',
               '2018-01-01 14:00:00', '2018-01-01 15:00:00',
               '2018-01-01 16:00:00', '2018-01-01 17:00:00',
               '2018-01-01 18:00:00', '2018-01-01 19:00:00',
               '2018-01-01 20:00:00', '2018-01-01 21:00:00',
               '2018-01-01 22:00:00', '2018-01-01 23:00:00',
               '2018-01-02 00:00:00', '2018-01-02 01:00:00',
               '2018-01-02 02:00:00', '2018-01-02 03:00:00',
               '2018-01-02 04:00:00', '2018-01-02 05:00:00',
               '2018-01-02 06:00:00', '2018-01-02 07:00:00',
               '2018-01-

48

In [108]:
ts.head(5)

2018-01-01 00:00:00    0
2018-01-01 01:00:00    1
2018-01-01 02:00:00    2
2018-01-01 03:00:00    3
2018-01-01 04:00:00    4
Freq: H, dtype: int32

In [109]:
ts.tail(5)

2018-01-02 19:00:00    43
2018-01-02 20:00:00    44
2018-01-02 21:00:00    45
2018-01-02 22:00:00    46
2018-01-02 23:00:00    47
Freq: H, dtype: int32

In [110]:
ts.resample('D').sum()

2018-01-01    276
2018-01-02    852
Freq: D, dtype: int32

In [111]:
ts.resample('D').mean()

2018-01-01    11.5
2018-01-02    35.5
Freq: D, dtype: float64

In [112]:
ts.resample('D').mean().resample('H').mean()

2018-01-01 00:00:00    11.5
2018-01-01 01:00:00     NaN
2018-01-01 02:00:00     NaN
2018-01-01 03:00:00     NaN
2018-01-01 04:00:00     NaN
2018-01-01 05:00:00     NaN
2018-01-01 06:00:00     NaN
2018-01-01 07:00:00     NaN
2018-01-01 08:00:00     NaN
2018-01-01 09:00:00     NaN
2018-01-01 10:00:00     NaN
2018-01-01 11:00:00     NaN
2018-01-01 12:00:00     NaN
2018-01-01 13:00:00     NaN
2018-01-01 14:00:00     NaN
2018-01-01 15:00:00     NaN
2018-01-01 16:00:00     NaN
2018-01-01 17:00:00     NaN
2018-01-01 18:00:00     NaN
2018-01-01 19:00:00     NaN
2018-01-01 20:00:00     NaN
2018-01-01 21:00:00     NaN
2018-01-01 22:00:00     NaN
2018-01-01 23:00:00     NaN
2018-01-02 00:00:00    35.5
Freq: H, dtype: float64

In [113]:
ts.resample('D').mean().resample('H').ffill()

2018-01-01 00:00:00    11.5
2018-01-01 01:00:00    11.5
2018-01-01 02:00:00    11.5
2018-01-01 03:00:00    11.5
2018-01-01 04:00:00    11.5
2018-01-01 05:00:00    11.5
2018-01-01 06:00:00    11.5
2018-01-01 07:00:00    11.5
2018-01-01 08:00:00    11.5
2018-01-01 09:00:00    11.5
2018-01-01 10:00:00    11.5
2018-01-01 11:00:00    11.5
2018-01-01 12:00:00    11.5
2018-01-01 13:00:00    11.5
2018-01-01 14:00:00    11.5
2018-01-01 15:00:00    11.5
2018-01-01 16:00:00    11.5
2018-01-01 17:00:00    11.5
2018-01-01 18:00:00    11.5
2018-01-01 19:00:00    11.5
2018-01-01 20:00:00    11.5
2018-01-01 21:00:00    11.5
2018-01-01 22:00:00    11.5
2018-01-01 23:00:00    11.5
2018-01-02 00:00:00    35.5
Freq: H, dtype: float64